### ISSUE TITLE
Displaced lane support in traffic light simulation

### ISSUE THREAD

**Issue by Elesbaan70** [CitiesSkylinesMods/TMPE#1392]
**Note** - This issue has been completely rewritten, and so some comments before 27-March-2022 may be outdated and irrelevant. A more extensive discussion of this issue can be found at https://github.com/CitiesSkylinesMods/TMPE/discussions/1428

### Description

Detect lanes that run in a nonstandard direction, and use them as a basis for traffic light grouping.

There are three use cases already identified for displaced lanes: Continuous Flow Intersections and Turnaround Lanes (both pictured below), and also Contraflow Interchanges. Diverging Diamond Interchanges are *not* an example of displaced lanes, because they involve only lane reversal, not a complex mixture of lane directions.

Entry into and exit from displaced lanes needs separate traffic light regulation for these scenarios:

* In advance of a Continuous Flow Intersection, traffic crossing over into the displaced far turn lane needs separate control from traffic remaining in standard lanes. This divides forward-moving traffic among multiple lights.
* After a Continuous Flow Intersection, traffic going straight starts out displaced and crosses back to the standard side, for which it needs separate control from the near-turn slip lane. This divides forward-moving traffic among multiple lights.
* At an intersection with a turnaround lane, the turns into and out of the displaced (turnaround) lane need separate control from the standard far turns. This divides "far"-turning traffic among multiple lights.

A theoretical condition exists where near-turning traffic turns into or out of a displaced lane. However, there seem to be no real-world use cases for this, so it is being omitted to avoid strange traffic light groupings that would be difficult to represent clearly in the UI.

### Definitions

**Forward Lane** - A lane for which the value of Lane.m_direction is Forward, Both, or AvoidBackward. This is represented in the asset editor by the Direction field.

**Backward Lane** - A lane for which the value of Lane.m_direction is Backward, Both, or AvoidForward. This is represented in the asset editor by the Direction field.

**Standard Road** - A road that is either one-way or that has exactly two sets of lanes, one forward and the other backward. Forward and backward may be reversed, and for the purposes of lane displacement that is still a standard road.

**Complex Road** - A road that has three or more sets of lanes in alternating directions.

**Standard Lane** - Any lane on a Standard Road. On a complex road, any lane that exists in the standard position in relation to opposing traffic. If there is only one set of lanes going in a given direction, they are always Standard lanes.

**Displaced Lane** - On a complex road, any lane that exists in a nonstandard position in relation to opposing traffic, when other lanes going the same direction are in the standard position. If there is only one set of lanes going in a given direction, they are never Displaced Lanes.

**Cross Left** - A traffic light lane grouping for forward-moving traffic that crosses into a displaced lane (out of a displaced lane in LHT).

**Cross Right** - A traffic light lane grouping for forward-moving traffic that crosses out of a displaced lane (into a displaced lane in LHT).

**Forward Displaced** - A traffic light lane grouping for forward-moving traffic that is in a displaced lane both before and after the node.

**Turn Into Displaced** - A traffic light lane grouping for far-turning traffic that enters a displaced lane.

**Turn Out of Displaced** -- A traffic light lane grouping for far-turning traffic that leaves a displaced lane.

#### Continuous Flow Intersection
Sometimes called a Displaced Left Turn
![image](https://user-images.githubusercontent.com/95266227/154823496-a5e058b0-ed89-4978-8f8c-a5d629ac8d53.png)

#### Turnaround Lane
A slip lane that connects pairs of one-way roads to facilitate U-turns
![image](https://user-images.githubusercontent.com/95266227/154823686-fc78a4c7-8425-4487-9632-79dcce8514b0.png)

### Displaced Lane Identification

Conceptually, lane displacement is based on identifying sets of lanes that run in opposing directions, and that is how they are described here and covered in unit tests. The implementation will be mathematical.

#### One-way and simple two-way roads

If only one or two sets of lanes exist, they are always Standard Lanes, even if they are reversed as in the case of a Diverging Diamond Interchange.

#### Roads with three sets of lanes in alternating directions

In this scenario, one direction will have two sets of lanes, and the other direction will have only one. In the direction with two sets of lanes, the set that is in a nonstandard position in relation to opposing traffic are considered displaced lanes.

#### Roads with four sets of lanes in alternating directions.

In this scenario, each direction has two distinct sets of lanes. They may be configured in one of two ways:

* If the outer lanes run in the standard direction (i.e., in the asset editor the leftmost lane is backward and the rightmost lane is forward), then the two inner sets of lanes are displaced. This is the configuration for a standard Continuous Flow Intersection.
* If the outer lanes run in the reverse direction (i.e., in the asset editor the leftmost lane is forward and the rightmost lane is backward), then the two outer sets of lanes are displaced. This is the configuration for Turnaround Lanes.

#### More than four sets of lanes

This implementation will not support more than four sets of lanes on a single prefab.

### Traffic Light Grouping

Traffic light grouping for displaced lanes will be based on the Lane Connector tool. This is based on the assumption that this type of intersection always involves the *intentional* assignment of lane connections. In the future, we could explore basing these lane groupings on the traffic AI's default behavior in the absence of explicit lane connections.

The traffic light simulation will attempt to eliminate groupings based on displaced lanes when they do not represent a distinct movement. For example, at the central node of a Continuous Flow Intersection, the left turns are Turn Out of Displaced, but since this applies to *all* of the left-turning lanes on a segment, the distinct grouping would not add functionality but would only make the UI more confusing.

### Lane Transitions

At a node where the Lane Connector tool has not been used, lane transitions between displaced and non-displaced lanes will be disallowed for all vehicle types when the node has only two segments AND the segments have matching displaced lane layouts. The number of lanes does not have to match, only the overall pattern of standard and displaced lanes.

### Graphics

CrossLeft, CrossRight
![image](https://user-images.githubusercontent.com/95266227/156866883-1fc59867-7694-4d6c-a305-c48feb5b4ea1.png) ![image](https://user-images.githubusercontent.com/95266227/156866894-f5a36f9b-fbe1-49ef-94ac-ea7c5ad75e78.png)

TurnOutOfDisplaced (RHT, LHT)
![image](https://user-images.githubusercontent.com/95266227/156866928-372da92b-ede1-4ca9-ae03-553c8d880fa6.png) ![image](https://user-images.githubusercontent.com/95266227/156866937-ae333e21-8aac-427e-909f-8a008458f06a.png)

TurnIntoDisplaced (RHT, LHT)
![image](https://user-images.githubusercontent.com/95266227/156866972-a85ac039-e5c1-429a-9016-e3b6756728d2.png) ![image](https://user-images.githubusercontent.com/95266227/156866975-b92d4084-7a82-4518-bb29-e4c868660ecc.png)

ForwardDisplaced (RHT, LHT)
![image](https://user-images.githubusercontent.com/95266227/156867026-6b30fe35-fe13-48b8-8dc4-c4dc7ebb8261.png) ![image](https://user-images.githubusercontent.com/95266227/156867031-c6af4a15-d3c2-4a8d-8be0-bdaa537032c1.png)

### Tasks

- `NetInfo` extensions
    - [x] Displaced lane detection
- LaneConnectionManager
    - [x] Raise an event when connections on a lane end change.
    - [x] Raise an event when the lane connection feature is enabled/disabled.
- [x] Identification and flagging of lane connections involving displaced lanes, in `LaneEndManager`.
    Also listens for LaneConnectionManager events to reset its cached data.
- [x] Removal of unmaintainable and unused public traffic light API.
    This needs a rollout plan in case there are unknown/surprise dependencies.
- [x] `CustomSegmentLights` groups lights by both `ExtVehicleInfo` and `NetLaneFlags`.
    Displacement-based groupings are folded into the main group if they don't conflict.
- Tool enhancements:
    - [x] Show infosigns for displaced lane connections
    - [x] When displaced lane lights have the same vehicle types as the main light, hide the vehicle type infosigns.
- Persistence
    - [x] Merge from `xml-persistence` branch
    - [x] Rework `CustomSegmentLightModel` to include `NetLaneFlags`
- `LaneConnectionManager`
    - [x] Allow `LaneConnectionManager` to be queried during load regardless of enabled state
- [ ] TTL Copy/Paste
- `RoutingManager`
    - Enter Displaced Lane Configuration
        - [ ] Inside turns prefer transition to displaced lane
        - [ ] Outside turns prefer transition to standard lane
        - [ ] Do not mix outgoing lane types
        - [ ] Lane selection logic for forward transitions: https://github.com/CitiesSkylinesMods/TMPE/discussions/1428#discussioncomment-2796679
    - Leave Displaced Lane Configuration
        - [ ] Lane selection logic for forward transitions: https://github.com/CitiesSkylinesMods/TMPE/discussions/1428#discussioncomment-2796763
    - Within Displaced Lane Configuration
        - Junctions
            - [x] Forward transitions to same lane type only
            - [ ] Turns favor transition to same lane type
            - [ ] Do not mix outgoing lane types
        - Middle and Bend Nodes
            - [x] Disallow lane transitions of any type into and out of displaced lanes at middle and bend nodes.
    - [ ] Use `RoutingManager` instead of `LaneConnectionManager` for TTL lane groupings
- Lane Connector stay-in-lane
    - [ ] Try to be smart about crossovers
- TTL Quick Setup
    - Continuous Flow Intersection
        - [ ] Two-way node with inner displaced lanes on one segment
        - [ ] Three- or four-way node with inner displaced lanes on one or more segments
    - Contraflow Interchange
        - To be addressed separately
    - Diamond Interchange with Turnaround Lane
        - To be addressed separately

**Comment by Elesbaan70** [comment]
@krzychu124, I've thought about this more based on our conversation on Discord, reexamined my use cases, and had a good look at the code.

Controlling traffic lights by lane would be really cool, but it's not realistic since the existing code treats it as a directional problem. But in reality, crossovers are a directional problem anyway, and reexamining my use cases confirms that. I could offer you some great use cases for traffic light control by lane, but this is not one of them.

A crossover is, in terms of traffic control, almost exactly the same thing as a far turn, and it should be treated as such. Both movements conflict with oncoming traffic, which is why they require a separate traffic light phase.

I will rewrite this feature request based on these findings.

**Comment by aubergine10** [comment]
Regarding lane traffic crossing in the junction causing conflict points: https://github.com/CitiesSkylinesMods/TMPE/issues/4

**Comment by Elesbaan70** [comment]
If this is implemented, Adaptive Networks should probably be given some related flag support. Not needed for this enhancement, but useful for asset creators.

**Comment by aubergine10** [comment]
Could you clarify the terminology here:

> * It is a forward lane whose position is greater than that of all backward lanes.
> * It is a backward lane whose position is less than that of all forward lanes.

Is `foward/backward lane` in relation to the final lane direction in relation to the segment containing that lane, or relative to the main junction ahead? What is meant by `position`?

**Comment by Elesbaan70** [comment]
"Position" means the value of the Position field in the editor. "Forward" and "Backward" are the directions as indicated in the editor.

**Comment by Elesbaan70** [comment]
I have added definitions for Position, Forward Lane, and Backward Lane.

**Comment by aubergine10** [comment]
I'm wondering if this feature could also provide a good opportunity to experiment with new traffic light editing UI?

Rather than using the floating traffic light icons, would it be better to 'highlight lanes' on the map, showing red/green (plus some other visual cue, such as fill or border style, for color blind users)? Toggling traffic light state for the lane would involve simply clicking the lane and would give immediate on-lane feedback (eg. the 'lane highlight' would change colour/etc)...?

**Comment by krzychu124** [comment]
I would create at least simplified version of overlaymanager mentioned in other issue. Btw, I've been experimenting with animated shader texture (scrollable texture that follows shape of path) to display custom animated thingy as we see entering into traffic routes view (or via Traffic Report mod)

**Comment by aubergine10** [comment]
> Btw, I've been experimenting with animated shader texture (scrollable texture that follows shape of path) to display custom animated thingy as we see entering into traffic routes view (or via Traffic Report mod)

Yesssss :) The arrows would start flowing when the light goes green. Want!

**Comment by Elesbaan70** [comment]
> I'm wondering if this feature could also provide a good opportunity to experiment with new traffic light editing UI?

Seems like a good idea on the one hand. On the other hand, maybe best not to needlessly link two features of significant effort that could exist independently of each other?

**Comment by Elesbaan70** [comment]
A work in progress that would implement this feature can be found here:

https://github.com/Elesbaan70/TMPE/tree/displaced-lanes

**Comment by Elesbaan70** [comment]
An additional requirement has been added this issue's main description, for the RoutingManager to prevent lane changes across oncoming traffic.

**Comment by kianzarrin** [comment]
I don't see it.
![image](https://user-images.githubusercontent.com/26344691/162604060-8eeaff74-88d6-469a-9ba2-b0a6bfd7fad8.png)

> RoutingManager to prevent lane changes across oncoming traffic.

Only on middle nodes.

**Comment by Elesbaan70** [comment]
The date shown is when it was originally posted. If you click on "edited" it will show the edit history.

The change is under the "Lane Transitions" heading and states that it only applies on nodes with two segments.

**Comment by Elesbaan70** [comment]
@aubergine10 please assign to me

**Comment by Elesbaan70** [comment]
Here's the wiki page. I'll improve this based on feedback.

[Loading and Saving Data](https://github.com/CitiesSkylinesMods/TMPE/wiki/Loading-and-Saving-Data)
