### ISSUE TITLE
Integration of Vanilla and TMPE priority roads

### ISSUE THREAD

**Issue by kianzarrin** [CitiesSkylinesMods/TMPE#542]
Currently when using the priority signs tool, holding shift highlights the road (or at least it should). if you Shift+click then it turns the whole highlighted road to priority road by requiring the connected roads to yield. It distinguishes between priority road and connected road by angle.  This is done using `SegmentTraverser` class. 

The vanilla game also has a feature to create priority road. but its done slightly differently. It allows you to click on a road and choose a road segment.  then puts stop signs on connecting roads.

As you can see in the pictures bellow there is a disconnect between Vanila and TMPE priority roads:
![round about segment](https://user-images.githubusercontent.com/26344691/68071296-ce952480-fd81-11e9-9842-dd9b06b146b0.png)
![semi roundabouts](https://user-images.githubusercontent.com/26344691/68071297-ce952480-fd81-11e9-840b-75f18705a8f2.png)
![hover issue long road](https://user-images.githubusercontent.com/26344691/68071298-ce952480-fd81-11e9-8d58-45fe0787cf7a.png)
![hover issue long road2](https://user-images.githubusercontent.com/26344691/68071299-ce952480-fd81-11e9-8786-8c99453ec756.png)

Each approach has advantages and disadvantages:
 - Vanila: slower but more flexible in terms of selecting what constitutes a priority road (lets call it vanilla road selector). It also cannot add yield signs.
 - TMPE: Its faster to use but less flexible. many people will resort to deleting part of their road in order to limit the length of the priority road. also in complex situation its hard to select what is the priority road. Its also inconsistent with Vanilla.

I suggest to integrate the TMPE and vanilla approaches. We can discuss what the final solution would look like. possible solutions are:
1. Best of both worlds: when you shift-click with TMPE priority sign tool, it modifies the path selected by the vanilla road selector.
2. Get rid of the TMPE shift modifier key and instead change the Vanilla UI so that you can choose what to do with the priority road ( eg: yield, stop, etc), .
3. Don't touch the game UI. instead modify the TMPE settings in terms of what a priority road should do( eg: yield, stop, etc). 
in approach 2 or 3 we can also add functionality for these closely  related issues: closely related issues : #541 #539 .

other related issues #29 #7

**Comment by kianzarrin** [comment]
please assign to me.

**Comment by kianzarrin** [comment]
I am trying to figure out how to get the selected road segment in my code.

**Comment by kianzarrin** [comment]
Found it!
![Screenshot (5)](https://user-images.githubusercontent.com/26344691/68076298-901c5b80-fdbb-11e9-9ed7-b6000083ddc4.png)

**Comment by kianzarrin** [comment]
I cannot access it from the code:
```
namespace testspce {
    using System.Diagnostics;
    using ColossalFramework;
    using UnityEngine;
    using UnityEngineInternal;
    using ColossalFramework;
    using ICities;
    public class testclass {
        private void testcode(uint segmentId, uint nodeId) {
            var a = Singleton<NetAdjust>.instance.m_segmentQueue; //error : m_segmentQueue does not exist
            var b = Singleton<NetManager>.instance.NetAdjust.m_segmentQueue; //error : m_segmentQueue does not exist
            var c = NetAdjust.m_segmentQueue; //error : m_segmentQueue does not exist
        }
    }
}
```
any ideas?

**Comment by kianzarrin** [comment]
OK Its a private member so I need to use reflection

**Comment by kianzarrin** [comment]
OK got reflection to work. the variable I am looking for is NetAdjust.tempPath there are other similar variables there too but tempPath is the one we can most easily traverse. 

The game can store multiple paths for different roads (Segments cannot be part of 2 paths). I had no luck so far trying to find out where all these paths are stored. I can only get the active path.

**Comment by brunoais** [comment]
I would keep the multi-click for different outcomes TMPE has. Usually, much faster to use than selecting from a menu.
I like the idea of integrating the vanilla priority road builder with TMPE's priority road.
But... I do want to keep the options for yield and stop signs the vanilla game has.

**Comment by kianzarrin** [comment]
@brunoais That's what I want too. I suspect that's how vast majority of people would like to use this tool in vast majority of situations. 
So its the best of both worlds option I talked above. If we want to do that I think I only need to look at the active `NetAdjust` path. less work for me :)

**Comment by kianzarrin** [comment]
I am nearly done with this:
The screenshot bellow shows my new UI. The drop box values are : None, Yield, Stop, All. The "ALL" option  will fix all traffic rules. The arrears both in Road adjust panel and Road world info panel because usually only one of them is visible.
![Screenshot (73)](https://user-images.githubusercontent.com/26344691/69304261-ac781f00-0c28-11ea-8ca7-88085413023a.png)

Any suggestions?

**Comment by aubergine10** [comment]
It's not very clear what the options are doing (unless you already know what they are doing).

Instead of a drop down list, why not use icon buttons? Something like:

> When joining this road, drivers should: 🛑 🔻 

When panel opens, or route altered, scan the "smaller" side-roads linked to the route to see what most of them are using: If that's stop or yield show the associated button as selected, otherwise neither button is selected.

* Clicking a selected button deselects it, effectively returning smaller-road junctions to vanilla
* Clicking a non-selected button will select it, applying all relevant customisations to smaller-road junctions

In case of a roundabout detection, a third icon could be added when applicable, for example: ⚪️. Clicking the roundabout button would apply special ruleset applicable to roundabouts.

**Comment by aubergine10** [comment]
Note also: When adding yield or stop rules, the vanilla stop rule (Junctions tab of Traffic Routes info view) should also be applied. TM:PE will still take precedence but most segment prefabs will show additional on-map signage/decals when the vanilla stop flag is set.

**Comment by kianzarrin** [comment]
THanks @aubergine10 . you are right. I have to trash my work and use your approach. I need One more Sprite for #541 with the icon of go through blocked junction and/or no left turn.

**Comment by aubergine10** [comment]
> The "ALL" option will fix all traffic rules.

Could you elaborate on this?

I assume that if user clicks one of the other three (yield, stop, roundabout) it would automatically apply relevant customisations for:

* Priority signs
* Junction restrictions
* Lane arrows (as per #538)
* And, potentially, even traffic lights where applicable?

**Comment by kianzarrin** [comment]
@aubergine10 
>>The "ALL" option will fix all traffic rules.

>Could you elaborate on this?

it does exactly what #541  does but for the segments selected by the user. that means no left turns go through blocked junctions no zebra crossing on avenue, yield, etc ... and its according to the settings set it in the options.

**Comment by aubergine10** [comment]
Are user's choices retained for the road? For example, if I click Yield button, it will set the existing smaller-roads to yield when entering the road, but what if I add new connecting roads, or alter the road route?

**Comment by kianzarrin** [comment]
>Are user's choices retained for the road? For example, if I click Yield button, it will set the existing smaller-roads to yield when entering the road, but what if I add new connecting roads, or alter the road route?

No, but this is not the case in vanilla case either. the vanilla priority road option does not remember your last choice. this is how The vanilla works:
- if the user turns on the priority road toggle, then put stop signs on all the roads that join the priory road.
- the next time the user selects the road if: all the roads connected to the current selection have stop signs then automatically turn on the priority button.
- if the user turns off the priority toggle then remove the stop signs.
- I think there is also a bug that sometimes it forgets to remove traffic lights.

I am not planning to remember the last choice either. not in my first commit at least.

**Comment by kianzarrin** [comment]
![road-edit-btns](https://user-images.githubusercontent.com/26344691/69559039-ec852c00-0fb1-11ea-95ef-b28eb7e3b0b2.png)
My new button textures to put in the `adjust road selection panel`

**Comment by aubergine10** [comment]
Some of those textures already exist, so we should reuse existing ones if possible.

**Comment by kianzarrin** [comment]
![Screenshot (107)](https://user-images.githubusercontent.com/26344691/69577215-9a0a3680-0fd6-11ea-86af-017acf7763ea.png)
My new UI.

Intended functionality:

- clicking on any button will highlight that button and set traffic rules. it also removes highlights from other buttons.
- clicking again on the button removes the highlight and unsets traffic rules.
- clicking on clear button will clear all traffic rules. This button cannot get activated
- modifying the road selection will remove highlight from all buttons
- the code does not remember past road selections. clicking on a different road selection removes highlight from all buttons.
- clikcing on roundabout button is like #539 
- clickin on enterblocked_allowed button is like #541 

tagging @aubergine10

things left to do:

- [ ] Hide Priority road toggle.
- [ ] put a label for the panels: "set traffic rules"
- [ ] Implement button functions (blocked by #541 #539 #553 )

**Comment by aubergine10** [comment]
Looking good!

#### Roundabout button

I would expect the roundabout button to only appear if the named road forms a closed loop.

#### Enter blocked junction button

Do we need the separate **Enter blocked junction** button? My assumption (and I think users will make the same assumption) would be that selecting either **Yield**, **Stop**, or **Roundabout**, would automatically add the **Enter blocked junction** where applicable.

#### Vanilla Stop signs

When applying our Yield/Stop/Roundabout rules, I would expect the vanilla **Stop** sign (as seen on Junctions tab of Traffic Routes info view) to be applied at any segments that are given a TM:PE-styled Stop or Yield sign.

This is to integrate with roads assets designed to adapt to yeilding/stopping traffic. A good example is the UK Roads Revived roads, which will show a "Give Way" sign and additional decals when vanilla Stop sign is placed.

#### What if junction has traffic lights?

My assumption is that any junctions with traffic lights will remain unaltered; they will not get Yield, Stop (or vanilla Stop) signs, and will retain their traffic light.

However, I note that TM:PE timed traffic lights has some integration with TM:PE priority signs (if enabled in mod options) so that might need some extra thought?

#### Vanilla priority road checkbox

I agree that the vanilla "Priority road" checkbox should be removed.

Note however, that vanilla game "remembers" the priority road setting - I just did a quick test and confirmed this.

At a guess, it just checks to see if all applicable side roads have a vanilla Stop sign set. Or it could be setting an as-yet undiscovered flag somewhere (on the road segments perhaps)? Either way, you will have to track down code that sets default state to avoid exceptions once that checkbox has been removed from UI.

If checkbox is removed from UI, disabling or unsubbing TM:PE from main menu should revive it.

#### Display existing state if possible

> This could be done as a later PR, as I expect it is somewhat cumbersome to implement.

I would expect it, if possible, to scan the road to see if _all_ smaller side roads are set to one of the configurations. That way I can click a road and see if anything needs updating (if icon is highlighted, I know all the side roads are already configured, otherwise I can choose what config to apply).

Note: _If_ vanilla sets an as-yet undiscovered 'Priority Road' flag somewhere, then we should ideally also set that flag should user choose either Yield, Stop or Roundabout.

Without this, I have no way of knowing if the whole road is configured as I expect it to be and would end up re-applying rules each time "just in case".

#### UI layout

In terms of UI, it might be worth having a method that adds an extra panel (with the lighter grey background like that shown on Adjust Roads tab) and then put everything in to that. That way, all the functionality will be gathered together coherently and we can add extra stuff to it in future if applicable. 

Rough mockup of panel contents:

> Which traffic rules should be applied to this road?
>  
> 🔻 🛑 ⚫️ =

Tooltips of icons could be something like (just an initial draft):

* Yield: Traffic on the road has priority; joining traffic must yield
* Stop: Traffic on the road has priority; joining traffic must stop
* Roundabout: Apply special roundabout rules
* Equal: Treat all traffic equally; remove any priority rules

On the Adjust Roads tab, the panel would be added below the existing vanilla panel. On the Road info popup, the panel would be added below the existing content.

**Comment by aubergine10** [comment]
Some additional stuff to check:

* What happens if user tries using this on tram/rail/monorail/metro/etc?
    * In vanilla, stand-alone dedicated tram tracks can be marked "Priority road"
    * In vanilla, train tracks can have stop signs, both at junctions (including the outer side of "X" junctions either side of stations), level crossings and tunnel entrances.
    * I've never personally tried on monorail or metro, so no idea what happens there.
* Speaking of level crossings, make sure to test those ;)
* Do the buttons auto-apply things like separate turning lanes and lane arrows where applicable (maybe via mod option?)
    * If so, I assume it will still allow traffic to cross to opposite side on small roads (or roads with m_canCrossLanes flag)?

**Comment by kianzarrin** [comment]
These buttons look so ugly! The back ground button shape is a circle that is barely bigger than the symbol itself. I think it should be a bigger square. Also the sprites do not have to be filled in.
![Screenshot (107)](https://user-images.githubusercontent.com/26344691/69577215-9a0a3680-0fd6-11ea-86af-017acf7763ea.png)

**Comment by kianzarrin** [comment]
I am struggling to find a good sprite to use for the button responsible for quick-setup of priority road. any ideas?
tagging @kvakvs @aubergine10

**Comment by kvakvs** [comment]
Make a temporary ugly sprite in paint.
Or someone can feel inspiration and combine 1-2 free icons for you in Ms Paint.

**Comment by kianzarrin** [comment]
@kvakvs well now I am going to use this:
![sign_priority](https://user-images.githubusercontent.com/26344691/72980760-d9d97880-3de3-11ea-8cb9-9391f1e87eec.png)

**Comment by kianzarrin** [comment]
New sprites 
![road-edit-btns2](https://user-images.githubusercontent.com/26344691/72986924-f5e41680-3df1-11ea-864d-88462195e462.png)

**Comment by kianzarrin** [comment]
I modified `LinearSpirte` to add support for disabled buttons. The buttons can now have 3 states(the number of states is configurable).
- State disabled: when user has not selected any road/roundabout
- State deactive: when the user has a valid road selection. Clicking will results in setting up traffic rules and sending the button to active state.
- State active: Clicking will clears the changes the user has done. ( in future we can have a more clever undo. related: #568).
![road-edit-btns3](https://user-images.githubusercontent.com/26344691/73109780-d4c41880-3f0c-11ea-87f0-01298bd04813.png).

Added Created `OnSelectionChange` event for when user changes path selection.

**Comment by kianzarrin** [comment]
This task is nearly complete. 
- [ ] I am going to improve the sprites a little bit more
- [ ] I will disable the yellow diamond button because it depends on #541. 
- [ ] The functionality of Clear button is limited (only removes priority signs) pending #623.
- [ ] I will enable traffic rule overlay when road selection panel is open even when the tool is not active

The images bellow show the round about button in disabled(selection is not a round about), enabled (selection is a roundabout), active states(round about rules applied). clicking an active button again will undo traffic rules (undo is simplistic pending #568)  

![Screenshot (335)](https://user-images.githubusercontent.com/26344691/73121192-4e491e80-3f80-11ea-9dae-92b61ea602e4.png)
![Screenshot (337)](https://user-images.githubusercontent.com/26344691/73121130-6ff5d600-3f7f-11ea-8125-c48df6984d5e.png)
![Screenshot (338)](https://user-images.githubusercontent.com/26344691/73121129-6f5d3f80-3f7f-11ea-9c27-d88657d1fb1e.png)
![Screenshot (339)](https://user-images.githubusercontent.com/26344691/73121128-6f5d3f80-3f7f-11ea-9057-fbf3a6b4b062.png)

**Comment by kvakvs** [comment]
Ok now that i've seen it on the real UI not just sprites.
The style you've chosen for icons, background, and size does not match game UI at all. Can you copy game colors more closely at least for the backgrounds?

**Comment by kianzarrin** [comment]
@kvakvs thanks for the feedback.
I wish to create pull review for this soon. Is there anything else you want to add?
tagging @aubergine10

**Comment by kianzarrin** [comment]
New sprites
![road-edit-btns](https://user-images.githubusercontent.com/26344691/73131558-dcbbaf80-4015-11ea-8e00-8e8b17ef8dc5.png)

**Comment by kianzarrin** [comment]
screenshots show how buttons appear.
![Screenshot (349)](https://user-images.githubusercontent.com/26344691/73132041-1db7c200-401e-11ea-9a7d-e1444cd6e9ee.png)\

Mass edit overlay is enable while road selection panel is active.
![Screenshot (348)](https://user-images.githubusercontent.com/26344691/73132042-1db7c200-401e-11ea-821e-716a250ced8e.png)

this work is complete. I will polish the code and put it for review.

**Comment by Goomig** [comment]
I don't even play this game, nor use any mods, but just some feedback. Those icons DO NOT match at all. If I used this mod, I would unsubscribe to this if those icons were posted.

**Comment by aubergine10** [comment]
And what would you make them look like @Goomig ? We're always open to suggestions :)

**Comment by Goomig** [comment]
Idk man they look really poppy

**Comment by Goomig** [comment]
They look to 'noticeable'

**Comment by kianzarrin** [comment]
I can make them smaller. I con design is not my specialty.

**Comment by aubergine10** [comment]
The UI stuff @kvakvs is working on should make button states easier.

**Comment by ItzNathaniel** [comment]
> I can make them smaller. Icon design is not my specialty.
> The colors are the same as game colors. The size is bigger. I was struggling with circular borders so I made it rectangle.
> 
> The game buttons have fewer states than my. when the game button is in active state it does not change face when mouse hovers or mouse is pressed.

I apologize for being a douche about the icons. They do look really nice, the only thing I would change is the gradient on the boxes. I'm getting a very nice Flat UI Icon.
